#!/bin/bash
echo "Enter a number: "
read a
echo "Enter a number: "
read b
sum=$((a+b))
echo "sum ="$sum
subtraction=$((a-b))
echo "subtraction ="$subtraction
mult=$((a*b))
echo "products ="$mult
div=$((a/b))
echo "division ="$div
