#!/bin/bash
echo "Enter a number: "
read a
echo "Enter a number: "
read b
sum=$((a+b))
echo "sum ="$sum 
sub=$((a-b))
echo "subtraction ="$sub
mult=$((a*b))
echo "product ="$mult
div=$((a/b))
echo "division ="$div
